version: '2.3'
services:
  database:
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: deck
      POSTGRES_USER: deck
      POSTGRES_PASSWORD: deck
  database-admin:
    image: dpage/pgadmin4:4.19
    volumes:
      - ./.docker/database-admin/servers.json:/pgadmin4/servers.json:ro
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '2345:80'
