databaseChangeLog:
  - changeSet:
      id: 1
      author: ml@infrastructr.dev
      comment: Creates table 'hosts'.
      changes:
        - createTable:
            tableName: hosts
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp with time zone
              - column:
                  name: updated_at
                  type: timestamp with time zone
              - column:
                  name: name
                  type: text
                  constraints:
                    nullable: false
              - column:
                  name: project_id
                  type: uuid
                  constraints:
                    nullable: false
        - addUniqueConstraint:
            tableName: hosts
            columnNames: name, project_id
            constraintName: hosts_name_project_id_key
