databaseChangeLog:
  - changeSet:
      id: 1
      author: ml@infrastructr.dev
      comment: Adds foreign keys to table 'playbooks'.
      changes:
        - addForeignKeyConstraint :
            baseTableName: playbooks
            baseColumnNames: project_id
            constraintName: fk_playbooks_project_id_projects_id
            referencedTableName: projects
            referencedColumnNames: id
